### ISSUE TITLE
Seek(k) returns the first item of the tree even if item's key is larger than k

### ISSUE THREAD

**Issue by Timoha** [cznic/b#6]
Based on the doc:
```
Seek returns an Enumerator positioned on an item such that k >= item's key.
```

However, here's a test that appears to be a special case with item's key > k:
```
func TestSeekBeforeFirst(t *testing.T) {
	r := TreeNew(cmp)
	r.Set(42, 314)
	enum, ok := r.Seek(10)
	if ok {
		t.Fatal("WTF")
	}
	k, v, err := enum.Next()
	t.Logf("K: %v, V: %v, Err: %v", k, v, err)
}
```
Output:
```
=== RUN   TestSeekBeforeFirst
--- PASS: TestSeekBeforeFirst (0.00s)
	all_test.go:181: K: 42, V: 314, Err: <nil>
```

Would be nice to update the doc about this behavior or even better have `nil, nil, io.EOF` returned.

**Comment by cznic** [comment]
> However, here's a test that appears to be a special case with **item's key > k**:

The observation is that `k >= item's key` means `item's key <= k`, not `item's key > k`.

AFAICT, the behavior seems correct to me. After `Seek(10)` (and up `Seek(41)`), the returned `Enumerator` is positioned *before* item `(42, 314)`, so `Next` returns that item. (`Seek(42)` should return an enumerator with the same position but an `ok == true` result and finally `Seek(43)` should return an enumerator positioned *after* the only item in the tree and `ok == false`).

IOW, `Seek(k)` prepares to enumerate, using `Next`, items with key >= `k`, that's why the resulting position is *before* an item with key >= `k`.

It may help to imagine the tree has two virtual items always present: a negative infinity item *before* the first item and a positive infinity *after* the last item. Considering these thougth items, the invariant "k >= item's key" holds.

Does it make sense?

Please feel free to propose documentation improvements. If you would like to send a PR, please include yourself in the `AUTHORS` and/or `CONTRIBUTORS` files, thank you.

**Comment by Timoha** [comment]
> The observation is that k >= item's key means item's key <= k, not item's key > k.

My bad, I meant to say that the test exposes a special case where we get `item's key > k` instead of `item's key <= k`.

> After Seek(10) (and up Seek(41)), the returned Enumerator is positioned before item (42, 314), so Next returns that item.

So shouldn't the item before item (42, 314) be a `negative infinity item` as (42, 314) is the first item? And since `Next()` returns the current item and then moves the enumerator, it should return negative infinity?

**Comment by cznic** [comment]
When the `Next` or `Prev` would have to return infinity it says `io.EOF` ;-)

**Comment by cznic** [comment]
> And since Next() returns the current item and then moves the enumerator, it should return negative infinity?

`Next` moves in collating order, `Prev` in the reversed collating order. IOW, `Next` can never attempt to return negative infinity, only the positive one. Invert for `Prev`.

**Comment by Timoha** [comment]
Alright, I see now and agree with `Seek`+`Next` pattern, but it seems like the `Seek`+`Prev` doesn't hold to similar logic unless I'm missing something.

Here're couple examples:
```
func TestSeekBeforeFirst(t *testing.T) {
	r := TreeNew(cmp)
	r.Set(42, 314)
	enum, ok := r.Seek(10)
	if ok {
		t.Fatal("WTF")
	}
	k, v, err := enum.Prev()
	t.Logf("K: %v, V: %v, Err: %v", k, v, err)
}
```
Output:
```
=== RUN   TestSeekBeforeFirst
--- PASS: TestSeekBeforeFirst (0.00s)
	all_test.go:181: K: 42, V: 314, Err: <nil>
```
and
```
func TestSeekBeforeFirst(t *testing.T) {
	r := TreeNew(cmp)
	r.Set(42, 314)
	r.Set(45, 314)
	enum, ok := r.Seek(43)
	if ok {
		t.Fatal("WTF")
	}
	k, v, err := enum.Prev()
	t.Logf("K: %v, V: %v, Err: %v", k, v, err)
}
```
Output:
```
=== RUN   TestSeekBeforeFirst
--- PASS: TestSeekBeforeFirst (0.00s)
	all_test.go:178: K: 45, V: 314, Err: <nil>
```
I would expect in the first case to get `io.EOF`, and in second case `(42, 314)`

**Comment by cznic** [comment]
Well, it seems like a bug in `Prev` to me as well :disappointed: 

Not sure I've ever used `Prev` at all. Are there are any tests for i? Will investigate as time permits (give me a couple of days). Feel free to look into the issue if you like to.

**Comment by Timoha** [comment]
Ok cool, I'll try to take a look this week. Might be a tricky problem though, since when we `Seek` we don't know if `Next` or `Prev` is going to be called

**Comment by Timoha** [comment]
Fixed by https://github.com/cznic/b/pull/7
